
cppcheck:
  stage: test
  allow_failure: true
  image: registry.gitlab.dockstudios.co.uk/pub/docker-images/cpp-static-code-analysis:latest
  script:
    - cppcheck --enable=all --error-exitcode=1 ./games/stickrpg
