stages:
  - Code Check
  - Build
  - Smoke Tests

Code Check:
  stage: Code Check
  only: external
  script: echo 1

Build:
  stage: Build
  only: external
  script: echo 1

Smoke Tests:
  stage: Smoke Tests
  only: external
  script: echo 1
  

