/*
 * StickGBC by Matt Comben is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License.
 * To view a copy of this license, visit
 * http://creativecommons.org/licenses/by-nc-nd/4.0/.
 */

/*

 BUILDING_MENU_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : building_menu_tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define buildingmenumapWidth 20
#define buildingmenumapHeight 18
#define buildingmenumapBank 0

extern unsigned char buildingmenumap[];

/* End of BUILDING_MENU_MAP.H */
