/*
 * StickGBC by Matt Comben is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License.
 * To view a copy of this license, visit
 * http://creativecommons.org/licenses/by-nc-nd/4.0/.
 */

/*

 ENDGAME_MAP.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : end_game.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define endgamemapWidth 20
#define endgamemapHeight 18
#define endgamemapBank 0

extern const unsigned char endgamemap[];

/* End of ENDGAME_MAP.H */
