/*
 * StickGBC by Matt Comben is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License.
 * To view a copy of this license, visit
 * http://creativecommons.org/licenses/by-nc-nd/4.0/.
 */

/*

 MAIN_MAP_SPRITE_TILESET.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 2

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* CGBpalette entries. */
const unsigned char mainmapspritetilesCGB[] =
{
  0x00,0x00,0x00
};
/* Start of tile array. */
const unsigned char mainmapspritetiles[] =
{
  0x81,0x00,0x99,0x00,0xA5,0x18,0xC3,0x3C,
  0x42,0x3C,0x24,0x18,0x18,0x00,0x00,0x00,
  0x0F,0x00,0x18,0x00,0x24,0x18,0x42,0x3C,
  0x42,0x3C,0x24,0x18,0x18,0x00,0x0F,0x00,
  0x18,0x00,0x10,0x00,0x28,0x10,0x45,0x38,
  0x03,0x7C,0x44,0x38,0x28,0x10,0x00,0x00
};

/* End of MAIN_MAP_SPRITE_TILESET.C */
