/*
 * StickGBC by Matt Comben is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License.
 * To view a copy of this license, visit
 * http://creativecommons.org/licenses/by-nc-nd/4.0/.
 */

/*

 MAIN_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 80 x 55
   Tile set      : C:\GBDK\games\stickrpg\main_tiles.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MainMapWidth 80
#define MainMapHeight 55
#define MainMapBank 0

extern unsigned char MainMap[];

/* End of MAIN_MAP.H */
