/*
 * StickGBC by Matt Comben is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License.
 * To view a copy of this license, visit
 * http://creativecommons.org/licenses/by-nc-nd/4.0/.
 */

/*

 MAIN_MAP_SPRITE_TILESET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 13

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define mainmapspritetilesBank 0

/* Super Gameboy palette 0 */
#define mainmapspritetilesSGBPal0c0 6076
#define mainmapspritetilesSGBPal0c1 8935
#define mainmapspritetilesSGBPal0c2 6596
#define mainmapspritetilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define mainmapspritetilesSGBPal1c0 6076
#define mainmapspritetilesSGBPal1c1 8935
#define mainmapspritetilesSGBPal1c2 6596
#define mainmapspritetilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define mainmapspritetilesSGBPal2c0 6076
#define mainmapspritetilesSGBPal2c1 8935
#define mainmapspritetilesSGBPal2c2 6596
#define mainmapspritetilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define mainmapspritetilesSGBPal3c0 6076
#define mainmapspritetilesSGBPal3c1 8935
#define mainmapspritetilesSGBPal3c2 6596
#define mainmapspritetilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define mainmapspritetilesCGBPal0c0 32767
#define mainmapspritetilesCGBPal0c1 0
#define mainmapspritetilesCGBPal0c2 32104
#define mainmapspritetilesCGBPal0c3 1006

/* Gameboy Color palette 1 */
#define mainmapspritetilesCGBPal1c0 32767
#define mainmapspritetilesCGBPal1c1 0
#define mainmapspritetilesCGBPal1c2 11297
#define mainmapspritetilesCGBPal1c3 1006

/* Gameboy Color palette 2 */
#define mainmapspritetilesCGBPal2c0 32767
#define mainmapspritetilesCGBPal2c1 0
#define mainmapspritetilesCGBPal2c2 1101
#define mainmapspritetilesCGBPal2c3 1006

/* Gameboy Color palette 3 */
#define mainmapspritetilesCGBPal3c0 32767
#define mainmapspritetilesCGBPal3c1 1088
#define mainmapspritetilesCGBPal3c2 1006
#define mainmapspritetilesCGBPal3c3 719

/* Gameboy Color palette 4 */
#define mainmapspritetilesCGBPal4c0 6076
#define mainmapspritetilesCGBPal4c1 8935
#define mainmapspritetilesCGBPal4c2 6596
#define mainmapspritetilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define mainmapspritetilesCGBPal5c0 6076
#define mainmapspritetilesCGBPal5c1 8935
#define mainmapspritetilesCGBPal5c2 6596
#define mainmapspritetilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define mainmapspritetilesCGBPal6c0 6076
#define mainmapspritetilesCGBPal6c1 8935
#define mainmapspritetilesCGBPal6c2 6596
#define mainmapspritetilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define mainmapspritetilesCGBPal7c0 6076
#define mainmapspritetilesCGBPal7c1 8935
#define mainmapspritetilesCGBPal7c2 6596
#define mainmapspritetilesCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char mainmapspritetilesCGB[];
/* Start of tile array. */
extern const unsigned char mainmapspritetiles[];

/* End of MAIN_MAP_SPRITE_TILESET.H */
