/*
 * StickGBC by Matt Comben is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License.
 * To view a copy of this license, visit
 * http://creativecommons.org/licenses/by-nc-nd/4.0/.
 */

/*

 MAIN_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 72 x 57
   Tile set      : C:\GBDK\games\stickrpg\main_tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mainmapWidth 72
#define mainmapHeight 57
#define mainmapBank 0

extern unsigned char mainmap[];

/* End of MAIN_MAP.H */
