/*
 * StickGBC by Matt Comben is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License.
 * To view a copy of this license, visit
 * http://creativecommons.org/licenses/by-nc-nd/4.0/.
 */

/*

 OPENING_SCREEN_MAP.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : opening_screen_tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define openingscreenmapWidth 20
#define openingscreenmapHeight 18
#define openingscreenmapBank 0

extern const unsigned char openingscreenmap[];

/* End of OPENING_SCREEN_MAP.H */
