/*
 * StickGBC by Matt Comben is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License.
 * To view a copy of this license, visit
 * http://creativecommons.org/licenses/by-nc-nd/4.0/.
 */

/*

 SPRITE_TILESET.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* CGBpalette entries. */
unsigned char spritetilesCGB[] =
{
  0x00
};
/* Start of tile array. */
unsigned char spritetiles[] =
{
  0x81,0x00,0x99,0x00,0xBD,0x00,0xFF,0x00,
  0x7E,0x00,0x3C,0x00,0x18,0x00,0x00,0x00
};

/* End of SPRITE_TILESET.C */
