/*
 * StickGBC by Matt Comben is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License.
 * To view a copy of this license, visit
 * http://creativecommons.org/licenses/by-nc-nd/4.0/.
 */

/*

 SPRITE_TILESET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 2

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define spritetilesBank 0

/* Super Gameboy palette 0 */
#define spritetilesSGBPal0c0 6076
#define spritetilesSGBPal0c1 8935
#define spritetilesSGBPal0c2 6596
#define spritetilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define spritetilesSGBPal1c0 6076
#define spritetilesSGBPal1c1 8935
#define spritetilesSGBPal1c2 6596
#define spritetilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define spritetilesSGBPal2c0 6076
#define spritetilesSGBPal2c1 8935
#define spritetilesSGBPal2c2 6596
#define spritetilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define spritetilesSGBPal3c0 6076
#define spritetilesSGBPal3c1 8935
#define spritetilesSGBPal3c2 6596
#define spritetilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define spritetilesCGBPal0c0 32767
#define spritetilesCGBPal0c1 0
#define spritetilesCGBPal0c2 1230
#define spritetilesCGBPal0c3 1006

/* Gameboy Color palette 1 */
#define spritetilesCGBPal1c0 6076
#define spritetilesCGBPal1c1 23254
#define spritetilesCGBPal1c2 13741
#define spritetilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define spritetilesCGBPal2c0 6076
#define spritetilesCGBPal2c1 8935
#define spritetilesCGBPal2c2 6596
#define spritetilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define spritetilesCGBPal3c0 6076
#define spritetilesCGBPal3c1 8935
#define spritetilesCGBPal3c2 6596
#define spritetilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define spritetilesCGBPal4c0 6076
#define spritetilesCGBPal4c1 8935
#define spritetilesCGBPal4c2 6596
#define spritetilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define spritetilesCGBPal5c0 6076
#define spritetilesCGBPal5c1 8935
#define spritetilesCGBPal5c2 6596
#define spritetilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define spritetilesCGBPal6c0 6076
#define spritetilesCGBPal6c1 8935
#define spritetilesCGBPal6c2 6596
#define spritetilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define spritetilesCGBPal7c0 6076
#define spritetilesCGBPal7c1 8935
#define spritetilesCGBPal7c2 6596
#define spritetilesCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char spritetilesCGB[];
/* Start of tile array. */
extern unsigned char spritetiles[];

/* End of SPRITE_TILESET.H */
